---
development:
  dialect: postgres
  database: ruhamayared/project1
  user: ruhamayared
  password: v2_428qt_qBt6csKntU8ajigh5CycAEB
  host: db.bit.io
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgresql://ruhamayared:v2_428qt_qBt6csKntU8ajigh5CycAEB@db.bit.io:5432/ruhamayared/project1?sslmode=require"}}

production:
  url: {{envOr "DATABASE_URL" "postgresql://ruhamayared:v2_428qt_qBt6csKntU8ajigh5CycAEB@db.bit.io:5432/ruhamayared/project1?sslmode=disable"}}
